FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TZ=Asia/Kathmandu
ENV PYTHONPATH=/app
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

# Install system dependencies (Debian)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc g++ cmake \
    curl \
    libpq-dev \
    libffi-dev \
    libssl-dev \
    python3-dev \
    libjpeg-dev \
    zlib1g-dev \
    libopenblas-dev \
    liblapack-dev \
    gdal-bin libgdal-dev \
    proj-bin proj-data libproj-dev \
    libgeos-dev \
    tzdata \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry && \
    poetry config virtualenvs.create false

# Copy Poetry files
COPY pyproject.toml poetry.lock /app/

# Install Python dependencies
RUN poetry install --no-interaction --no-ansi --no-root

# Copy project
COPY . /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
