FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

ENV TZ=Asia/Kathmandu

ENV PYTHONPATH=/app

ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

# Install required system packages
RUN apk update && apk add --no-cache \
    bash \
    tzdata make \
    gcc g++ musl-dev libffi-dev openssl-dev \
    curl cargo \
    python3-dev jpeg-dev zlib-dev rust \
    postgresql-dev \
    geos geos-dev \
    gdal gdal-dev \
    proj proj-dev \
    build-base openssh

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry && \
    poetry config virtualenvs.create false && \
    poetry config installer.max-workers 10

# Copy Poetry files
COPY pyproject.toml poetry.lock /app/

# Install Python dependencies
RUN poetry install --no-interaction --no-ansi --no-root

# Copy project AFTER dependencies
COPY . /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]